//
// Autogenerated by Thrift Compiler (0.9.3)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
var thrift = require('thrift');
var Thrift = thrift.Thrift;
var Q = thrift.Q;


var ttypes = module.exports = {};
ttypes.Roles = {
  'user' : 0,
  'admin' : 15,
  'sales' : 1,
  'auditor' : 2,
  'editor' : 4,
  'tbker' : 8,
  'tuditorAndEditor' : 6,
  'siteTagEditor' : 16
};
ttypes.Rights = {
  'admin' : 7,
  'view' : 1,
  'audit' : 2,
  'edit' : 4,
  'tbk' : 8,
  'siteTagEdit' : 16
};
